Char         ::=        #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]
S            ::=        (#x20 | #x9 | #xD | #xA)+
Comment	   ::=   	'<!--' ((Char - '-') | ('-' (Char - '-')))* '-->'
